name: GitHubActionsの検証用フロー
on:
  push:
    branches:
       - github-action-外部通信
  workflow_dispatch:
jobs:
  my-cron-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # # 任意の処理を行う
      # - name: Run Script
      #   id  : run-script
      #   run : node ./index.js
      # 上の処理が失敗した時だけ Slack 通知する
      - name: 成功時にSlackへ通知する
        id: slack-success
        uses: slackapi/slack-github-action@v1.14.0
        if: success()
        with:
          payload: "{ "\attachments"\:[{"\fallback"\:"\fallback Test"\,"\pretext"\:"\att *achm* ents _Test_ <!here> <https://www.jbcchd.co.jp/|This is jbcchd link>"\,"\color"\:"\#D00000"\,"\fields"\:[{"\title"\:"\attachment01"\,"\value"\:"\This is attachment"\}]}]}"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      # - name: 成功時にSlackへ通知する
      #   id: slack-failure
      #   uses: slackapi/slack-github-action@v1.14.0
      #   if: failure()
      #   with:
      #     payload: "{\"text\":\"処理が失敗しました。\"}"
      #   env:
      #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}