# GitHub Actionsの名前
name: github-actions-first

on:
#   実行のトリガーとなるアクション（push,pr）のmainブランチで実行
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # 実行される処理の単位（日本語はダメ）
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # ソースコードをチェックアウトする（/home/runner/work/backendapp-nodejs/backendapp-nodejs）
      # actions/checkout@v2はここ（https://github.com/actions/checkout）
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      # Runs a single command using the runners shell　（日本語OK）
      - name: スクリプト1
        id: aaaa
        run: echo Hello, world!
      - name: file-search
        id: bbb
        run: |
          ls -al
          ls -al /
          pwd