# GitHub Actionsの名前
name: github-actions-first

on:
#   実行のトリガーとなるアクション（push,pr）のmainブランチで実行
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # 実行される処理の単位（日本語も行ける？）
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # ソースコードをチェックアウトする（/home/runner/work/backendapp-nodejs/backendapp-nodejs）
      - name: Checkout
        uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: スクリプト1
        run: echo Hello, world!
      - name: file-search
        run: |
          ls -al
          ls -al /
          pwd