# GitHub Actionsの名前
name: github-actions-first

on:
#   実行のトリガーとなるアクション（push,pr）のmainブランチで実行
  push:
    branches:
       - main
       - dev
    paths-ignore:
      - ".github/**"
      - ".gitignore"
      - "README.md"
    paths:
      - "index.js"
      - "Dockerfile"
  # pull_request:
  #   branches:
  #     - dev
  #     - main
  workflow_dispatch:
# 結局ECRへのログイン時regionを指定しないとエラーが出る
# Error: Missing region in config
# env:
#   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }} 
#   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
#   AWS_DEFAULT_REGION: ap-northeast-1

jobs: # 日本語はダメ
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
        # 環境変数に追加される
        # secretsはGitHubのSettings⇒Secrets⇒ripository Secretから設定可能
      - name: aws configure の設定 dev環境
        if: github.ref == 'refs/heads/dev'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - name: 環境ごとの変数　dev環境
        if: github.ref == 'refs/heads/dev'
        id: env-dev
        run: echo '::set-output name=TEST_ENV::100'
      - name: aws configure の設定 dev環境
        if: github.ref == 'refs/heads/main'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - name: 環境ごとの変数　prod環境
        if: github.ref == 'refs/heads/main'
        id: env-prod
        run: echo '::set-output name=TEST_ENV::100'
      # ソースコードをチェックアウトする（/home/runner/work/backendapp-nodejs/backendapp-nodejs）
      # actions/checkout@v2はここ（https://github.com/actions/checkout）
      - name: Checkout
        uses: actions/checkout@v2
        
      # id⇒参照時に利用　name⇒表示目的
      - name: スクリプト1
        id: aaaa
        run: echo ${{ steps.env-dev.outputs.TEST_ENV }}
      
      - name: AWS ECRにログイン
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # - name: ビルド後ECRにPush
      #   id: build-image
      #   env:
      #     DOCKER_BUILDKIT: 1
      #     ECR_REGISTRY: 831318551697.dkr.ecr.ap-northeast-1.amazonaws.com
      #     ECR_REPOSITORY: kenta-dev
      #     IMAGE_TAG: ${{ github.sha }}
      #   run: |
      #     # latest と github.sha でタグをふる場合
      #     docker build \
      #         --cache-from=$ECR_REGISTRY/$ECR_REPOSITORY:latest --build-arg BUILDKIT_INLINE_CACHE=1 \
      #         -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
      #     docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
      #     docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
      #     echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"